### ISSUE TITLE
it translation

### ISSUE THREAD

**Issue by albanobattistella** [alexkdeveloper/desktop-files-creator#10]
Hi,

the Italian translation it is not fully translated.
could you check?
thanks!
Albano

![Schermata da 2022-02-15 20-55-42](https://user-images.githubusercontent.com/34811668/154141484-70ea7ca2-a8c1-49c8-8ba9-25c4d86ca98c.png)

**Comment by alexkdeveloper** [comment]
Hi!
Most likely, this is due to the presence of a colon at the end of the word. There is no colon in the translation files, but it is present in the interface file. In text labels, a colon is not required for switches. I will try to solve this problem in the next update of the application.
