### ISSUE TITLE
Description for NoDisplay and Terminal

### ISSUE THREAD

**Issue by vanillajonathan** [alexkdeveloper/desktop-files-creator#23]
It may not be obvious to users what the `NoDisplay` and `Terminal` option does.
It would be good if the user interface described these two options.

**Comment by alexkdeveloper** [comment]
Thanks)
I think it makes sense to change the text labels to more understandable ones. For example, instead of the NoDisplay label, apply the label "Do not display in the menu" and write "Launch in Terminal" instead of Terminal. Or there is an option to apply tooltips for these labels.

**Comment by vanillajonathan** [comment]
Yeah, that would clarify things.

The issue is closed, but I see no commits related to it.

**Comment by alexkdeveloper** [comment]
The repository has been updated.
