### ISSUE TITLE
Icons missing on fedora

### ISSUE THREAD

**Issue by trickypr** [alexkdeveloper/desktop-files-creator#35]
![image](https://user-images.githubusercontent.com/23250792/205803226-4d25b5c0-e460-46fb-b39a-639a64e5ab35.png)

Installed via flatpak, my system theme is Adwaita. Are there any other details I can provide to help debug this?

**Comment by alexkdeveloper** [comment]
Hi!
Try to launch the application through the terminal using the command:
`flatpak run com.github.alexkdeveloper.desktop-files-creator`

**Comment by trickypr** [comment]
By default there are no logs. If I run with `G_MESSAGES_DEBUG=all` I get:

```
(desktop-files-creator:2): GLib-GIO-DEBUG: 22:36:50.058: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(desktop-files-creator:2): GVFS-DEBUG: 22:36:50.113: org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

(desktop-files-creator:2): GLib-GIO-DEBUG: 22:36:50.113: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
(desktop-files-creator:2): Adwaita-DEBUG: 22:36:50.185: Setting org.freedesktop.appearance.color-scheme of type u not found
(desktop-files-creator:2): Adwaita-DEBUG: 22:36:50.222: Setting org.gnome.desktop.interface.color-scheme of type s not found
(desktop-files-creator:2): Adwaita-DEBUG: 22:36:50.265: Setting org.gnome.desktop.a11y.interface.high-contrast of type b not found
```

Edit:
I have installed [Icon Library](https://flathub.org/apps/details/org.gnome.design.IconLibrary), and it doesn't seem to include `folder-open-symbolic`. Perhaps these icons are no longer shipped with adwaita / libadwaita by default or are specific to ubuntu's icon theme?

Edit 2:
Nope, setting up the Yaru theme didn't seem to fix it, probably something off on my system then.

**Comment by alexkdeveloper** [comment]
Now I switched to Adwaita. Installed the app. All the badges are in place. Most likely, flatpak has some problems with themes. Try to override with the commands:
```
flatpak override --filesystem=$HOME/.themes
flatpak override --filesystem=$HOME/.icons
```

**Comment by trickypr** [comment]
That did not appear to do anything, even after copying the contents of `/usr/share/[icons|themes]` to the relevant local directories.

**Comment by trickypr** [comment]
I have managed to reproduce this in a different gtk app, so this is a system config thing. Sorry about that/

**Comment by trickypr** [comment]
If anyone is running into this, make sure you have `xdg-desktop-portal-gtk` running. For detailed instructions see "Ensuring portals are running" in the [gentoo wiki](https://wiki.gentoo.org/wiki/Flatpak#Desktop_integration_for_Wayland)
