### ISSUE TITLE
Validation error regarding use of "Encoding"

### ISSUE THREAD

**Issue by Newbytee** [alexkdeveloper/desktop-files-creator#40]
When building a Flatpak package using an icon generated using this program, I get the following validation error in the log:
```
WARNING: Failed to validate desktop file /mnt/storage/Programming/windsond-desktop-git/packaging-data/build/export/share/applications/io.sparv.WindsondDesktop.desktop: /mnt/storage/Programming/windsond-desktop-git/packaging-data/build/export/share/applications/io.sparv.WindsondDesktop.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
```
I guess this field just should be removed?

**Comment by alexkdeveloper** [comment]
Yes, you can delete it.

This item is considered outdated. Here is the link to the specification:
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.0.html#deprecated-items

**Comment by Newbytee** [comment]
Yeah, but wouldn't it make sense for this app to not generate the field in the first place then?

**Comment by alexkdeveloper** [comment]
This will be removed in future versions.

This is just a warning, not an error. This should not affect the operation of your application in any way.

**Comment by Newbytee** [comment]
Absolutely :) Just thought I would make an issue since fixing deprecation warnings usually is good. I did indeed just remove it locally.
